/** UI copy in Bahasa Indonesia */

export const ui = {
  brand: "Survei",
  skipToContent: "Loncat ke konten",

  // Landing
  landingHeadline: "Ini bukan G-Form, tapi mirip G-Form",
  landingSub:
    "Buat formulir, bagikan tautan, kumpulkan jawaban — tanpa ribet.",
  getStarted: "Mulai",
  signIn: "Masuk",
  goToDashboard: "Ke dasbor",

  // Auth
  signInTitle: "Masuk ke akun Anda",
  signUpTitle: "Buat akun Survei",
  continueWithGoogle: "Lanjutkan dengan Google",
  signUpWithGoogle: "Daftar dengan Google",
  or: "atau",
  email: "Email",
  password: "Kata sandi",
  name: "Nama",
  yourName: "Nama Anda",
  yourEmail: "anda@contoh.com",
  yourPassword: "Kata sandi Anda",
  atLeast6Chars: "Minimal 6 karakter",
  signInWithEmail: "Masuk dengan email",
  createWithEmail: "Buat akun dengan email",
  creatingAccount: "Membuat akun…",
  signingIn: "Sedang masuk…",
  connecting: "Menghubungkan…",
  newToSurvei: "Baru di Survei?",
  createAccount: "Buat akun",
  alreadyHaveAccount: "Sudah punya akun?",
  signOut: "Keluar",
  signingOut: "Sedang keluar…",
  authInvalidEmail: "Masukkan alamat email yang valid.",
  authWrongCredentials: "Email atau kata sandi salah.",
  authTooManyRequests:
    "Terlalu banyak percobaan. Coba lagi dalam beberapa menit.",
  authSignInFailed: "Tidak bisa masuk. Silakan coba lagi.",
  authEmailInUse: "Email itu sudah terdaftar. Coba masuk.",
  authWeakPassword: "Kata sandi minimal 6 karakter.",
  authCreateAccountFailed: "Tidak bisa membuat akun. Silakan coba lagi.",
  googleSignInCancelled: "Masuk Google dibatalkan.",
  googlePopupBlocked:
    "Pop-up diblokir. Izinkan pop-up untuk situs ini dan coba lagi.",
  googleAccountExists:
    "Akun dengan email ini sudah ada. Masuk dengan email/kata sandi.",
  googleUnauthorizedDomain:
    "Domain ini tidak diizinkan untuk masuk Google. Tambahkan di pengaturan Firebase Auth.",
  googleProviderDisabled:
    "Masuk Google belum diaktifkan. Aktifkan provider Google di Firebase Authentication.",
  googlePopupFailed:
    "Jendela Google tidak bisa terhubung. Izinkan pop-up, atau buka Survei lewat localhost.",
  googleSignInFailed: "Tidak bisa masuk dengan Google. Silakan coba lagi.",
  googleSessionFailed:
    "Berhasil masuk dengan Google, tapi membuat sesi gagal. Periksa konfigurasi Firebase Admin di server.",

  // Nav / shell
  mainNav: "Utama",
  forms: "Formulir",
  backToForms: "← Formulir",
  yourFormsCaption: "Formulir Anda",

  // Dashboard
  yourForms: "Formulir Anda",
  dashboardHint: "Buat, terbitkan, dan kelola formulir milik Anda.",
  viewGuide: "Lihat panduan",
  onboardingStepOf: (n: number, total: number) => `Langkah ${n} dari ${total}`,
  onboardingSkip: "Lewati",
  onboardingBack: "Kembali",
  onboardingNext: "Lanjut",
  onboardingStart: "Mulai buat formulir",
  onboardingClose: "Tutup panduan",
  onboardingSteps: [
    {
      title: "Selamat datang di Survei",
      body: "Survei membantu Anda membuat formulir, membagikan tautan, dan melihat jawaban — tanpa spreadsheet.",
    },
    {
      title: "Buat formulir baru",
      body: "Dari dasbor, pilih Formulir baru. Judul dan deskripsi bisa diedit langsung di kartu paling atas.",
    },
    {
      title: "Susun pertanyaan & bagian",
      body: "Tambah pertanyaan dari bilah di samping kartu. Gunakan bagian agar responden mengisi halaman demi halaman.",
    },
    {
      title: "Tema & batas respons",
      body: "Di Pengaturan, pilih warna tema. Aktifkan “Batasi 1 respons per orang” jika setiap browser hanya boleh mengirim sekali.",
    },
    {
      title: "Terbitkan, bagikan, lihat jawaban",
      body: "Terbitkan untuk mendapat tautan pendek. Respons tampil di tab Respons, dan bisa diekspor ke CSV. Pratinjau meniru tampilan responden.",
    },
  ] as const,
  newForm: "Formulir baru",
  creating: "Membuat…",
  noFormsYet: "Belum ada formulir",
  noFormsHint: "Buat satu, tambah pertanyaan, lalu terbitkan dan bagikan tautannya.",
  title: "Judul",
  status: "Status",
  updated: "Diperbarui",
  actions: "Aksi",
  questionsCount: (n: number) =>
    `${n} pertanyaan`,
  draft: "Draf",
  live: "Aktif",
  closed: "Ditutup",
  published: "Terbit",
  copyLink: "Salin tautan pendek",
  copied: "Tersalin!",
  shareMenu: "Bagikan",
  shareWhatsApp: "Bagikan ke WhatsApp",
  copyCaption: "Salin teks undangan",
  captionCopied: "Teks undangan tersalin",
  downloadShareCard: "Unduh kartu unggahan",
  showQrCode: "Tampilkan QR",
  downloadQrCode: "Unduh QR",
  shareQrTitle: "QR formulir",
  shareQrHint:
    "Pindai dengan kamera ponsel. Untuk cetak atau poster, gunakan Unduh QR (resolusi tinggi).",
  shareQrAlt: (title: string) => `Kode QR untuk formulir ${title}`,
  shareQrFailed: "Tidak bisa membuat kode QR. Coba lagi.",
  shareNeedsPublish: "Terbitkan dulu untuk membagikan tautan.",
  startFromTemplate: "Mulai dari template",
  templateEventTitle: "Pendaftaran acara",
  templateEventDescription: "Daftar kehadiran acara. Isi nama dan nomor HP.",
  templateEventConfirmation: "Terima kasih. Pendaftaran Anda sudah kami terima.",
  templateEventSection: "Data peserta",
  templateCensusTitle: "Pendataan singkat",
  templateCensusDescription: "Pendataan nama, HP, dan wilayah.",
  templateCensusConfirmation: "Terima kasih. Data Anda sudah tercatat.",
  templateCensusSection: "Data diri",
  templateFeedbackTitle: "Umpan balik kegiatan",
  templateFeedbackDescription: "Berikan penilaian dan saran untuk kegiatan ini.",
  templateFeedbackConfirmation: "Terima kasih atas masukan Anda.",
  templateFeedbackSection: "Penilaian",
  templateNameLabel: "Nama lengkap",
  templatePhoneLabel: "Nomor HP",
  templateEmailLabel: "Email",
  templateWilayahLabel: "Wilayah / paroki",
  templateAttendLabel: "Apakah Anda akan hadir?",
  templateAttendYes: "Ya, saya hadir",
  templateAttendNo: "Tidak bisa hadir",
  templateRatingLabel: "Nilai kegiatan (5 = sangat baik)",
  templateCommentLabel: "Saran atau komentar",
  uniqueEmailHelp: "Pakai email yang sama jika mengisi ulang — hanya satu kali.",
  uniquePhoneHelp: "Pakai nomor HP aktif. Satu nomor hanya bisa terdaftar sekali.",
  uniqueByLabel: "Cara membatasi 1 respons",
  uniqueByBrowser: "Satu kali per browser",
  uniqueByPhone: "Satu kali per nomor HP",
  uniqueByEmail: "Satu kali per email",
  uniqueAlreadyUsed: "Nilai ini sudah terdaftar pada formulir ini.",
  validPhone: "Masukkan nomor HP yang valid",
  attendance: "Daftar hadir",
  attendanceName: "Nama",
  attendanceContact: "HP / email",
  attendanceTime: "Waktu",
  printAttendance: "Cetak daftar hadir",
  receiptTitle: "Bukti kirim",
  receiptId: "Kode",
  receiptTime: "Waktu kirim",
  copyReceipt: "Salin ringkasan",
  printReceipt: "Cetak bukti",
  receiptCopied: "Ringkasan tersalin",
  shortLink: "Tautan pendek",
  couldNotCreateShortLink: "Tidak bisa membuat tautan pendek. Coba lagi.",
  edit: "Edit",
  open: "Buka",
  duplicate: "Duplikat",
  delete: "Hapus",
  deleteConfirm: (title: string) =>
    `Hapus “${title}”? Tindakan ini tidak bisa dibatalkan.`,
  somethingWentWrongGeneric: "Terjadi kesalahan",

  // Form editor
  publish: "Terbitkan",
  publishing: "Menerbitkan…",
  reopen: "Buka lagi",
  close: "Tutup",
  openForm: "Buka formulir",
  publishToGetLink: "Terbitkan untuk mendapat tautan berbagi",
  linkCopied: "Tautan disalin",
  linkCopiedReady: "Tautan disalin — siap dibagikan.",
  couldNotCopyLink: "Tidak bisa menyalin tautan",
  untitledForm: "Formulir tanpa judul",
  addDescription: "+ Tambah deskripsi",
  descriptionPlaceholder: "Tambah deskripsi singkat (opsional)",
  formTitle: "Judul formulir",
  description: "Deskripsi",
  saving: "Menyimpan…",
  saved: "Tersimpan",
  saveFailed: "Gagal menyimpan",

  tabQuestions: "Pertanyaan",
  tabPreview: "Pratinjau",
  tabResponses: "Respons",
  tabSettings: "Pengaturan",
  tabResponsesCount: (n: number) => `Respons (${n})`,
  formSections: "Bagian editor formulir",

  // Builder
  questions: "Pertanyaan",
  questionN: (n: number) => `Pertanyaan ${n}`,
  sectionN: (n: number) => `Bagian ${n}`,
  sectionTitle: "Judul bagian",
  sectionTitlePlaceholder: "Bagian tanpa judul",
  sectionDescription: "Deskripsi bagian",
  sectionDescriptionOptional: "(opsional)",
  sectionDescriptionPlaceholder: "Teks di atas pertanyaan pada halaman ini",
  addSection: "+ Tambah bagian",
  addSectionHere: "Tambah bagian di sini",
  deleteSection: "Hapus bagian",
  deleteSectionN: (n: number) => `Hapus bagian ${n}`,
  deleteSectionConfirm: (title: string, n: number) =>
    `Hapus ${title} beserta ${n} pertanyaannya?`,
  deleteUntitledSectionConfirm: (n: number) =>
    `Hapus bagian ini beserta ${n} pertanyaannya?`,
  keepOneSection: "Minimal satu bagian",
  moveSectionUp: (n: number) => `Naikkan bagian ${n}`,
  moveSectionDown: (n: number) => `Turunkan bagian ${n}`,
  untitledSection: "Bagian tanpa judul",
  emptySectionHint: "Belum ada pertanyaan di bagian ini.",
  sectionBecomesPage:
    "Setiap bagian menjadi halaman terpisah saat responden mengisi formulir.",
  nextSectionBreak: "Halaman berikutnya",
  sectionPageOf: (n: number, total: number) => `Bagian ${n} dari ${total}`,
  atLeastOneSection: "Tambah minimal satu bagian",
  maxSectionsReached: "Paling banyak 20 bagian",
  questionNeedsSection: "Pertanyaan harus berada di sebuah bagian",
  duplicateSectionIds: "ID bagian tidak boleh sama",
  label: "Label",
  type: "Jenis",
  required: "Wajib",
  helpText: "Teks bantuan",
  helpTextOptional: "(opsional)",
  helpPlaceholder: "Petunjuk di bawah pertanyaan",
  options: "Opsi",
  optionN: (n: number) => `Opsi ${n}`,
  remove: "Hapus",
  addOption: "Tambah opsi",
  moveUp: "Naik",
  moveDown: "Turun",
  keepOneQuestion: "Minimal satu pertanyaan",
  deleteQuestion: "Hapus pertanyaan",
  addQuestion: "+ Tambah pertanyaan",
  addQuestionTool: "Tambah pertanyaan",
  addSectionTool: "Tambah bagian",
  formTools: "Alat formulir",
  duplicateQuestion: "Duplikat",
  duplicateQuestionN: (n: number) => `Duplikat pertanyaan ${n}`,
  questionPrompt: "Pertanyaan",
  orPickType: "Atau pilih jenis…",
  addSpecificType: "Tambah jenis pertanyaan tertentu",
  preview: "Pratinjau",
  previewForm: "Pratinjau formulir",
  livePreview: "Pratinjau formulir langsung",
  previewHint: "Tampilan yang dilihat responden. Jawaban di sini tidak terkirim.",
  addQuestionToPreview: "Tambah pertanyaan untuk melihat pratinjau.",
  fixQuestionErrors: "Perbaiki error pertanyaan untuk menyimpan",
  moveQuestionUp: (n: number) => `Naikkan pertanyaan ${n}`,
  moveQuestionDown: (n: number) => `Turunkan pertanyaan ${n}`,
  deleteQuestionN: (n: number) => `Hapus pertanyaan ${n}`,
  removeOptionN: (n: number) => `Hapus opsi ${n}`,
  yourAnswer: "Jawaban Anda",
  selectOption: "Pilih opsi",
  untitledQuestion: "Pertanyaan tanpa judul",

  questionTypes: {
    short_text: "Teks singkat",
    long_text: "Teks panjang",
    multiple_choice: "Pilihan ganda",
    checkboxes: "Kotak centang",
    dropdown: "Dropdown",
    range: "Rentang",
    email: "Email",
    number: "Angka",
    date: "Tanggal",
    file_upload: "Unggah file",
  } as const,

  chooseFile: "Pilih file",
  changeFile: "Ganti file",
  uploadingFile: "Mengunggah…",
  fileReady: "File siap",
  removeFile: "Hapus file",
  fileUploadHint: "Maks. 10 MB · gambar, PDF, Word, Excel, TXT, CSV",
  downloadFile: "Unduh file",
  invalidFileAnswer: "File tidak valid",

  // Settings
  settingsHint:
    "Judul dan deskripsi diedit di kartu formulir pada tab Pertanyaan. Terbitkan dan bagikan dari bilah di atas.",
  formTheme: "Tema formulir",
  formThemeHint:
    "Warna ini dipakai di halaman isi publik dan tab Pratinjau.",
  formHeaderImage: "Gambar header",
  formHeaderImageHint:
    "Tampil di bagian atas formulir publik. Jika kosong, garis warna tema dipakai.",
  chooseHeaderImage: "Unggah gambar",
  removeHeaderImage: "Hapus gambar",
  headerImageHint:
    "JPG, PNG, GIF, atau WebP · maks. 5 MB · dioptimalkan otomatis saat unggah · rasio lebar disarankan (mis. 3:1)",
  headerImageRequired: "Pilih gambar untuk diunggah",
  headerImageUploadFailed: "Gagal mengunggah gambar header",
  headerImageTooLarge: "Gambar header maksimal 5 MB",
  headerImageTypeInvalid: "Gunakan JPG, PNG, GIF, atau WebP",
  invalidHeaderImage: "Gambar tidak valid",
  formThemes: {
    teal: "Teal (Survei)",
    forest: "Hutan",
    ocean: "Laut",
    sunset: "Senja",
    grape: "Anggur",
    slate: "Batu",
    paper: "Kertas",
  } as const,
  afterSubmit: "Setelah kirim",
  confirmationMessage: "Pesan konfirmasi",
  confirmationHint: "Ditampilkan setelah seseorang mengirim respons.",
  responsesLimit: "Batas respons",
  limitOneResponse: "Batasi 1 respons per orang",
  limitOneResponseHint:
    "Di browser yang sama, seseorang hanya bisa mengirim sekali. Menghapus cookie atau memakai perangkat lain tetap bisa mengirim lagi.",
  alreadySubmitted: "Anda sudah mengirim respons",
  alreadySubmittedBody:
    "Formulir ini hanya menerima satu respons dari browser ini.",
  moreActions: "Aksi lainnya",
  deleteForm: "Hapus formulir",
  deleteFormConfirm: (title: string) =>
    `Hapus “${title}”? Respons juga akan dihapus.`,

  // Collaboration
  collaborators: "Kolaborator",
  collaboratorsHint:
    "Undang orang lain lewat email untuk mengedit formulir dan melihat respons. Hanya pemilik yang bisa mengelola kolaborator.",
  collaboratorEmailPlaceholder: "nama@contoh.com",
  inviteCollaborator: "Undang",
  invitingCollaborator: "Mengundang…",
  collaboratorInvited: "Undangan terkirim",
  collaboratorInviteCopied: "Tautan undangan disalin",
  collaboratorPending: "Menunggu",
  collaboratorActive: "Aktif",
  collaboratorRemove: "Hapus",
  collaboratorRemoveConfirm: (email: string) =>
    `Hapus ${email} dari kolaborator formulir ini?`,
  collaboratorInvalidEmail: "Masukkan alamat email yang valid.",
  collaboratorCannotInviteSelf: "Anda tidak bisa mengundang diri sendiri.",
  collaboratorInviteNotFound: "Undangan tidak ditemukan atau sudah kedaluwarsa.",
  collaboratorInviteEmailMismatch:
    "Undangan ini untuk email lain. Masuk dengan akun yang sesuai.",
  collaboratorNotFound: "Kolaborator tidak ditemukan.",
  collaboratorSharedBadge: "Dibagikan",
  collaboratorEditorBadge: "Kolaborator",
  collaboratorInviteTitle: "Undangan kolaborasi",
  collaboratorInviteBody: (inviter: string, formTitle: string) =>
    `${inviter} mengundang Anda untuk mengedit formulir “${formTitle}”.`,
  collaboratorInviteAccept: "Terima undangan",
  collaboratorInviteAccepting: "Menerima…",
  collaboratorInviteSignIn: "Masuk untuk menerima",
  collaboratorInviteWrongAccount: (email: string) =>
    `Undangan ini untuk ${email}. Masuk dengan akun tersebut.`,
  collaboratorInviteAlreadyActive: "Anda sudah menjadi kolaborator formulir ini.",
  collaboratorInviteOpenForm: "Buka formulir",
  collaboratorInviteEmailSubject: (formTitle: string) =>
    `Undangan mengedit “${formTitle}” di Survei`,
  collaboratorInviteEmailGreeting: "Halo,",
  collaboratorInviteEmailIntro: (inviterName: string, formTitle: string) =>
    `${inviterName} mengundang Anda untuk mengedit formulir “${formTitle}” di Survei.`,
  collaboratorInviteEmailCta: "Terima undangan",
  collaboratorInviteEmailFooter:
    "Jika Anda tidak mengharapkan email ini, abaikan saja.",
  collaboratorInviteEmailBody: (input: {
    inviterName: string;
    formTitle: string;
    inviteUrl: string;
  }) =>
    `${input.inviterName} mengundang Anda untuk mengedit formulir “${input.formTitle}” di Survei.\n\nTerima undangan: ${input.inviteUrl}`,
  collaboratorNoEmailConfigured:
    "Email belum dikonfigurasi — salin tautan undangan di bawah.",

  // Responses
  responses: "Respons",
  responseCount: (n: number) =>
    `${n} respons`,
  noResponsesYet: "Belum ada respons",
  noResponsesHint:
    "Bagikan tautan formulir yang sudah diterbitkan untuk mulai mengumpulkan jawaban.",
  exportCsv: "Ekspor CSV",
  summary: "Ringkasan",
  tabAnalysis: "Analisa & wawasan",
  tabResponseList: "Daftar respons",
  tabResponseByQuestion: "Per pertanyaan",
  tabResponseByIndividual: "Per individu",
  responseByQuestionCount: (n: number) => `${n} jawaban`,
  responseByQuestionTable: (label: string) => `Jawaban untuk ${label}`,
  answerCol: "Jawaban",
  analysisInsightsSubtitle: "Ringkasan survei dan wawasan dari respons terkumpul",
  analysisPerQuestionSubtitle: "Analisa per pertanyaan dari seluruh respons",
  analysisChoiceResponses: (n: number) => `${n} respons`,
  analysisDateFrom: "Dari",
  analysisDateTo: "Sampai",
  analysisExportPdf: "Ekspor PDF",
  analysisShareReport: "Bagikan laporan",
  analysisShareTitle: (title: string) => `Laporan analisa: ${title}`,
  analysisCompletionRate: "Tingkat penyelesaian",
  analysisCompletionHint: "Respons dengan semua pertanyaan wajib terisi",
  analysisAvgTime: "Rata-rata waktu isi",
  analysisAvgTimeHint: "Belum dilacak di versi ini",
  analysisCsatScore: "Skor CSAT",
  analysisNoScale: "Tidak ada pertanyaan skala",
  analysisResponsesLabel: "respons",
  analysisQualitative: "Wawasan jawaban terbuka",
  analysisQualitativeHint:
    "Analisis sentimen berbasis kata kunci (positif, netral, negatif) dan kata yang sering muncul",
  analysisNoDataInRange: "Tidak ada respons pada rentang tanggal ini.",
  sentimentPositive: "Positif",
  sentimentNeutral: "Netral",
  sentimentNegative: "Negatif",
  analysisOverview: "Ringkasan analisa",
  analysisTotalResponses: "Total respons",
  analysisPeriod: "Periode",
  analysisAverageScore: "Skor rata-rata",
  analysisAverage: "Rata-rata",
  analysisMedian: "Median",
  analysisMin: "Terendah",
  analysisMax: "Tertinggi",
  analysisScaleRange: (min: number, max: number) => `Rentang ${min}–${max}`,
  analysisScaleStats: (average: number, median: number, answered: number) =>
    `Rata-rata ${average} · median ${median} · ${answered} jawaban`,
  analysisTextResponseRate: "Tingkat jawaban teks",
  analysisSurveyScales: "Skala & penilaian",
  analysisSurveyOpenAnswers: "Jawaban terbuka",
  analysisTextStats: (answered: number, skipped: number, rate: number) =>
    `${answered} diisi · ${skipped} kosong · ${rate}% tingkat jawaban`,
  analysisTextQuestionsCount: (n: number) =>
    `${n} pertanyaan teks terbuka`,
  responseDetail: "Detail respons",
  backToList: "Kembali ke daftar",
  loading: "Memuat…",
  loadingForm: "Memuat formulir…",
  submitted: "Dikirim",
  previewCol: "Pratinjau",
  respondentCol: "Responden",
  respondentN: (n: number) => `Responden ${n}`,
  view: "Lihat",
  noAnswer: "Tidak ada jawaban",
  individualResponses: "Respons individu",
  deletedQuestion: "Pertanyaan dihapus",

  // Public fill
  responseRecorded: "Respons tercatat",
  formClosedTitle: "Formulir ditutup",
  formClosedBody: "Formulir ini ditutup dan tidak menerima respons.",
  submit: "Kirim",
  submitting: "Mengirim…",
  nextPage: "Selanjutnya",
  previewSubmitNote: "Ini pratinjau. Jawaban tidak dikirim.",
  previousPage: "Kembali",
  pageOf: (n: number, total: number) => `Halaman ${n} dari ${total}`,
  formProgress: "Progres formulir",
  requiredMark: "(wajib)",
  thisRequired: "Pertanyaan ini wajib diisi",
  validEmail: "Masukkan alamat email yang valid",
  validNumber: "Masukkan angka yang valid",
  networkError: "Kesalahan jaringan. Periksa koneksi dan coba lagi.",
  couldNotSubmit: "Tidak bisa mengirim. Silakan coba lagi.",
  respondTo: (title: string) => `Isi ${title}`,
  formMetaTitle: "Formulir",
  createAccountMeta: "Buat akun",
  dashboardMeta: "Dasbor",
  metaDescription: "Buat formulir, bagikan tautan, kumpulkan jawaban.",
  defaultUserName: "Pengguna Survei",
  formCopySuffix: "(salinan)",
  addQuestionBeforePublish: "Tambah minimal satu pertanyaan sebelum menerbitkan.",
  publishedCannotDraft:
    "Formulir terbit tidak bisa kembali ke draf. Tutup formulir saja.",
  invalidTextAnswer: "Jawaban teks tidak valid",
  answerTooLong: "Jawaban terlalu panjang",
  invalidEmailShort: "Email tidak valid",
  selectValidOption: "Pilih opsi yang valid",
  selectValidOptions: "Pilih opsi yang valid",
  unsupportedQuestionType: "Jenis pertanyaan tidak didukung",
  tooManySubmissions: "Terlalu banyak pengiriman. Coba lagi sebentar.",
  invalidJsonBody: "Isi JSON tidak valid",
  invalidSubmissionPayload: "Data kiriman tidak valid",
  fixHighlightedFields: "Perbaiki kolom yang ditandai",
  couldNotSaveResponse:
    "Tidak bisa menyimpan respons Anda. Silakan coba lagi.",
  formNotFound: "Formulir tidak ditemukan",
  formNotFoundHint:
    "Tautan mungkin salah, atau formulir masih berstatus draf.",
  backToSurvei: "Kembali ke Survei",
  pageNotFound: "Halaman tidak ditemukan",
  pageNotFoundHint:
    "Halaman itu tidak ada, atau Anda tidak punya akses.",
  somethingWrong: "Terjadi kesalahan",
  somethingWrongHint:
    "Kami menemui error tak terduga. Anda bisa coba lagi atau kembali ke beranda.",
  tryAgain: "Coba lagi",
  home: "Beranda",
  couldNotLoadDashboard: "Dasbor gagal dimuat",
  checkConnection:
    "Periksa koneksi dan pastikan variabel lingkungan MongoDB / Firebase sudah diisi.",

  signInRequired: "Perlu masuk terlebih dahulu",
  submittedAtCsv: "Dikirim pada",
  optionLabelRequired: "Label opsi wajib diisi",
  questionLabelRequired: "Label pertanyaan wajib diisi",
  atLeastOneOption: "Tambah minimal satu opsi",
  choiceNeedsOption: "Pertanyaan pilihan perlu minimal satu opsi",
  rangeNeedsBounds: "Atur nilai minimum dan maksimum rentang",
  validRangeBounds: "Rentang harus berupa bilangan bulat yang valid",
  validRangeValue: "Pilih nilai dalam rentang",
  rangeTooWide: "Rentang maksimal 20 nilai (mis. 1–10)",
  rangeMin: "Minimum",
  rangeMax: "Maksimum",
  rangeMinLabel: "Label minimum",
  rangeMaxLabel: "Label maksimum",
  rangeMinLabelPlaceholder: "Mis. Paling rendah",
  rangeMaxLabelPlaceholder: "Mis. Paling tinggi",
  rangeSummary: (min: number, max: number) => `Skala ${min}–${max}`,
  rangeSummaryWithLabels: (
    min: number,
    max: number,
    minLabel: string,
    maxLabel: string,
  ) => `${minLabel} (${min}) – ${maxLabel} (${max})`,
  atLeastOneQuestion: "Tambah minimal satu pertanyaan",

  invalidRequest: "Permintaan tidak valid",
  responseNotFound: "Respons tidak ditemukan",

  // Defaults
  defaultConfirmation: "Terima kasih — respons Anda sudah dikirim.",
  defaultQuestionLabel: "Pertanyaan tanpa judul",
  optionPrefix: (n: number) => `Opsi ${n}`,
} as const;
