/** UI copy in Bahasa Indonesia */

export const ui = {
  brand: "Forma",
  skipToContent: "Loncat ke konten",

  // Landing
  landingHeadline: "Formulir yang terasa seperti kertas, bekerja seperti perangkat lunak.",
  landingSub:
    "Buat formulir, bagikan tautan, kumpulkan jawaban — tanpa ribet.",
  getStarted: "Mulai",
  signIn: "Masuk",
  goToDashboard: "Ke dasbor",

  // Auth
  signInTitle: "Masuk ke akun Anda",
  signUpTitle: "Buat akun Forma",
  continueWithGoogle: "Lanjutkan dengan Google",
  signUpWithGoogle: "Daftar dengan Google",
  or: "atau",
  email: "Email",
  password: "Kata sandi",
  name: "Nama",
  yourName: "Nama Anda",
  yourEmail: "anda@contoh.com",
  yourPassword: "Kata sandi Anda",
  atLeast6Chars: "Minimal 6 karakter",
  signInWithEmail: "Masuk dengan email",
  createWithEmail: "Buat akun dengan email",
  creatingAccount: "Membuat akun…",
  signingIn: "Sedang masuk…",
  connecting: "Menghubungkan…",
  newToForma: "Baru di Forma?",
  createAccount: "Buat akun",
  alreadyHaveAccount: "Sudah punya akun?",
  signOut: "Keluar",
  signingOut: "Sedang keluar…",
  authInvalidEmail: "Masukkan alamat email yang valid.",
  authWrongCredentials: "Email atau kata sandi salah.",
  authTooManyRequests:
    "Terlalu banyak percobaan. Coba lagi dalam beberapa menit.",
  authSignInFailed: "Tidak bisa masuk. Silakan coba lagi.",
  authEmailInUse: "Email itu sudah terdaftar. Coba masuk.",
  authWeakPassword: "Kata sandi minimal 6 karakter.",
  authCreateAccountFailed: "Tidak bisa membuat akun. Silakan coba lagi.",
  googleSignInCancelled: "Masuk Google dibatalkan.",
  googlePopupBlocked:
    "Pop-up diblokir. Izinkan pop-up untuk situs ini dan coba lagi.",
  googleAccountExists:
    "Akun dengan email ini sudah ada. Masuk dengan email/kata sandi.",
  googleUnauthorizedDomain:
    "Domain ini tidak diizinkan untuk masuk Google. Tambahkan di pengaturan Firebase Auth.",
  googleSignInFailed: "Tidak bisa masuk dengan Google. Silakan coba lagi.",
  googleSessionFailed:
    "Berhasil masuk dengan Google, tapi membuat sesi gagal. Periksa konfigurasi Firebase Admin di server.",

  // Nav / shell
  mainNav: "Utama",
  forms: "Formulir",
  backToForms: "← Formulir",
  yourFormsCaption: "Formulir Anda",

  // Dashboard
  yourForms: "Formulir Anda",
  dashboardHint: "Buat, terbitkan, dan kelola formulir milik Anda.",
  newForm: "Formulir baru",
  creating: "Membuat…",
  noFormsYet: "Belum ada formulir",
  noFormsHint: "Buat satu, tambah pertanyaan, lalu terbitkan dan bagikan tautannya.",
  title: "Judul",
  status: "Status",
  updated: "Diperbarui",
  actions: "Aksi",
  questionsCount: (n: number) =>
    `${n} pertanyaan`,
  draft: "Draf",
  live: "Aktif",
  closed: "Ditutup",
  published: "Terbit",
  copyLink: "Salin tautan pendek",
  copied: "Tersalin!",
  shortLink: "Tautan pendek",
  couldNotCreateShortLink: "Tidak bisa membuat tautan pendek. Coba lagi.",
  edit: "Edit",
  open: "Buka",
  duplicate: "Duplikat",
  delete: "Hapus",
  deleteConfirm: (title: string) =>
    `Hapus “${title}”? Tindakan ini tidak bisa dibatalkan.`,
  somethingWentWrongGeneric: "Terjadi kesalahan",

  // Form editor
  publish: "Terbitkan",
  publishing: "Menerbitkan…",
  reopen: "Buka lagi",
  close: "Tutup",
  openForm: "Buka formulir",
  publishToGetLink: "Terbitkan untuk mendapat tautan berbagi",
  linkCopied: "Tautan disalin",
  linkCopiedReady: "Tautan disalin — siap dibagikan.",
  couldNotCopyLink: "Tidak bisa menyalin tautan",
  untitledForm: "Formulir tanpa judul",
  addDescription: "+ Tambah deskripsi",
  descriptionPlaceholder: "Tambah deskripsi singkat (opsional)",
  formTitle: "Judul formulir",
  description: "Deskripsi",
  saving: "Menyimpan…",
  saved: "Tersimpan",
  saveFailed: "Gagal menyimpan",

  tabQuestions: "Pertanyaan",
  tabResponses: "Respons",
  tabSettings: "Pengaturan",
  tabResponsesCount: (n: number) => `Respons (${n})`,
  formSections: "Bagian editor formulir",

  // Builder
  questions: "Pertanyaan",
  questionN: (n: number) => `Pertanyaan ${n}`,
  label: "Label",
  type: "Jenis",
  required: "Wajib",
  helpText: "Teks bantuan",
  helpTextOptional: "(opsional)",
  helpPlaceholder: "Petunjuk di bawah pertanyaan",
  options: "Opsi",
  optionN: (n: number) => `Opsi ${n}`,
  remove: "Hapus",
  addOption: "Tambah opsi",
  moveUp: "Naik",
  moveDown: "Turun",
  keepOneQuestion: "Minimal satu pertanyaan",
  deleteQuestion: "Hapus pertanyaan",
  addQuestion: "+ Tambah pertanyaan",
  orPickType: "Atau pilih jenis…",
  addSpecificType: "Tambah jenis pertanyaan tertentu",
  preview: "Pratinjau",
  previewForm: "Pratinjau formulir",
  livePreview: "Pratinjau formulir langsung",
  addQuestionToPreview: "Tambah pertanyaan untuk melihat pratinjau.",
  fixQuestionErrors: "Perbaiki error pertanyaan untuk menyimpan",
  moveQuestionUp: (n: number) => `Naikkan pertanyaan ${n}`,
  moveQuestionDown: (n: number) => `Turunkan pertanyaan ${n}`,
  deleteQuestionN: (n: number) => `Hapus pertanyaan ${n}`,
  removeOptionN: (n: number) => `Hapus opsi ${n}`,
  yourAnswer: "Jawaban Anda",
  selectOption: "Pilih opsi",
  untitledQuestion: "Pertanyaan tanpa judul",

  questionTypes: {
    short_text: "Teks singkat",
    long_text: "Teks panjang",
    multiple_choice: "Pilihan ganda",
    checkboxes: "Kotak centang",
    dropdown: "Dropdown",
    email: "Email",
    number: "Angka",
    date: "Tanggal",
    file_upload: "Unggah file",
  } as const,

  chooseFile: "Pilih file",
  changeFile: "Ganti file",
  uploadingFile: "Mengunggah…",
  fileReady: "File siap",
  removeFile: "Hapus file",
  fileUploadHint: "Maks. 10 MB · gambar, PDF, Word, Excel, TXT, CSV",
  downloadFile: "Unduh file",
  invalidFileAnswer: "File tidak valid",

  // Settings
  settingsHint:
    "Judul dan deskripsi diedit di bagian atas halaman. Terbitkan dan bagikan dari bilah di atas.",
  afterSubmit: "Setelah kirim",
  confirmationMessage: "Pesan konfirmasi",
  confirmationHint: "Ditampilkan setelah seseorang mengirim respons.",
  moreActions: "Aksi lainnya",
  deleteForm: "Hapus formulir",
  deleteFormConfirm: (title: string) =>
    `Hapus “${title}”? Respons juga akan dihapus.`,

  // Responses
  responses: "Respons",
  responseCount: (n: number) =>
    `${n} respons`,
  noResponsesYet: "Belum ada respons",
  noResponsesHint:
    "Bagikan tautan formulir yang sudah diterbitkan untuk mulai mengumpulkan jawaban.",
  exportCsv: "Ekspor CSV",
  summary: "Ringkasan",
  responseDetail: "Detail respons",
  backToList: "Kembali ke daftar",
  loading: "Memuat…",
  loadingForm: "Memuat formulir…",
  submitted: "Dikirim",
  previewCol: "Pratinjau",
  view: "Lihat",
  noAnswer: "Tidak ada jawaban",
  individualResponses: "Respons individu",
  deletedQuestion: "Pertanyaan dihapus",

  // Public fill
  responseRecorded: "Respons tercatat",
  formClosedTitle: "Formulir ditutup",
  formClosedBody: "Formulir ini ditutup dan tidak menerima respons.",
  submit: "Kirim",
  submitting: "Mengirim…",
  requiredMark: "(wajib)",
  thisRequired: "Pertanyaan ini wajib diisi",
  validEmail: "Masukkan alamat email yang valid",
  validNumber: "Masukkan angka yang valid",
  networkError: "Kesalahan jaringan. Periksa koneksi dan coba lagi.",
  couldNotSubmit: "Tidak bisa mengirim. Silakan coba lagi.",
  respondTo: (title: string) => `Isi ${title}`,
  formMetaTitle: "Formulir",
  createAccountMeta: "Buat akun",
  dashboardMeta: "Dasbor",
  metaDescription: "Buat formulir, bagikan tautan, kumpulkan jawaban.",
  defaultUserName: "Pengguna Forma",
  formCopySuffix: "(salinan)",
  addQuestionBeforePublish: "Tambah minimal satu pertanyaan sebelum menerbitkan.",
  publishedCannotDraft:
    "Formulir terbit tidak bisa kembali ke draf. Tutup formulir saja.",
  invalidTextAnswer: "Jawaban teks tidak valid",
  answerTooLong: "Jawaban terlalu panjang",
  invalidEmailShort: "Email tidak valid",
  selectValidOption: "Pilih opsi yang valid",
  selectValidOptions: "Pilih opsi yang valid",
  unsupportedQuestionType: "Jenis pertanyaan tidak didukung",
  tooManySubmissions: "Terlalu banyak pengiriman. Coba lagi sebentar.",
  invalidJsonBody: "Isi JSON tidak valid",
  invalidSubmissionPayload: "Data kiriman tidak valid",
  fixHighlightedFields: "Perbaiki kolom yang ditandai",
  couldNotSaveResponse:
    "Tidak bisa menyimpan respons Anda. Silakan coba lagi.",
  formNotFound: "Formulir tidak ditemukan",
  formNotFoundHint:
    "Tautan mungkin salah, atau formulir masih berstatus draf.",
  backToForma: "Kembali ke Forma",
  pageNotFound: "Halaman tidak ditemukan",
  pageNotFoundHint:
    "Halaman itu tidak ada, atau Anda tidak punya akses.",
  somethingWrong: "Terjadi kesalahan",
  somethingWrongHint:
    "Kami menemui error tak terduga. Anda bisa coba lagi atau kembali ke beranda.",
  tryAgain: "Coba lagi",
  home: "Beranda",
  couldNotLoadDashboard: "Dasbor gagal dimuat",
  checkConnection:
    "Periksa koneksi dan pastikan variabel lingkungan MongoDB / Firebase sudah diisi.",

  signInRequired: "Perlu masuk terlebih dahulu",
  submittedAtCsv: "Dikirim pada",
  optionLabelRequired: "Label opsi wajib diisi",
  questionLabelRequired: "Label pertanyaan wajib diisi",
  atLeastOneOption: "Tambah minimal satu opsi",
  choiceNeedsOption: "Pertanyaan pilihan perlu minimal satu opsi",
  atLeastOneQuestion: "Tambah minimal satu pertanyaan",

  invalidRequest: "Permintaan tidak valid",
  responseNotFound: "Respons tidak ditemukan",

  // Defaults
  defaultConfirmation: "Terima kasih — respons Anda sudah dikirim.",
  defaultQuestionLabel: "Pertanyaan tanpa judul",
  optionPrefix: (n: number) => `Opsi ${n}`,
} as const;
